version: '3'
services:
  mysql:
    image: mysql:8.3.0
    container_name: b2broker_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b2broker_backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/wallet
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
volumes:
  mysql_data: